version: "3"
 
services: 
  app:
    build: .
    container_name: app
    volumes: 
      - .:/var/www
    networks: 
      - app-network
    # entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    # environment: 
    #   - DB_HOST=db
    #   - DB_DATABASE=laravel
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=root
    depends_on: 
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    entrypoint: dockerize -template ./.docker/nginx/.nginx.conf.tmpl:/etc/nginx/conf.d
    environment: 
      - HOST=APP
      - PORT=9000
    ports: 
      - "8000:80"
    volumes: 
      - .:/var/www   
    networks:
      - app-network      
    depends_on: 
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports: 
      - "3306:3306"
    volumes: 
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - app-network

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks: 
      - app-network


networks:       
  app-network:
    driver: bridge